services:
  users:
    build: ./users-service
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_db
    depends_on:
      - users-db

  users-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    volumes:
      - users_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    depends_on:
      - users-db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  users_data:
  pgadmin_data:
